# Setup
title:               CCLHM0057-2020.1
tagline:             'História da América: Colonização e Resistência'
description:         'Site do curso CCLHM0057 - História da América: Colonização e Resistência, semestre 2020.1, do IHL/UNILAB.'
url:                 http://ericbrasiln.github.io
baseurl:             'http://ericbrasiln.github.io/lanyon/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Eric Brasil
  url:               https://twitter.com/ericbrasiln
  email:             profericbrasil@unilab.edu.br

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
